### ISSUE TITLE
Custom mobs not spawning

### ISSUE THREAD

**Issue by KingOfMyGames** [DRE2N/DungeonsXL#1005]
**Description**

I added two custom mob spawn command in the externalMobProviders in the config, but neither seems to work correctly (it says  that it summoned the mob in the console but nothing actually happens).

**Reproduce**

1. Create a new dungeon with /dxl create
2. Place [ready] sign, [mob]/creeper/0,1,EB/D5 sign
3. Place [ready] sign, [mob]/creeper/0,1,TE/D5 sign
4. Leave edit mode with /dxl leave
5. Test with /dxl play
6. Trigger ready sign and get close to the location of the spawn signs

**Expected behavior**

summon 1 invisible creeper riding a bee, and 1 normal creeper

**Screenshots / GIFs / videos**

![image](https://user-images.githubusercontent.com/43274091/114237234-11015e80-9983-11eb-8e45-fc7d2d2f75e7.png)

**Relevant configuration files**

```
externalMobProviders: 
  EB: "summon %mob% %block_x% %block_y% %block_z% {Fuse:5s,ExplosionRadius:3b,ActiveEffects:[{Id:14,Amplifier:0,Duration:999999, ShowParticles: 0b}],Passengers:[{id:bee}]}"
  TE: "summon %mob% %block_x% %block_y% %block_z%"
  TE2: "summon %mob% %block_x% %block_y% %block_z% {ActiveEffects:[{Id:14,Amplifier:0,Duration:999999, ShowParticles: 0b}]}"

```
