### ISSUE TITLE
keepInventoryOnDeath didn't work every time

### ISSUE THREAD

**Issue by GuazP** [DRE2N/DungeonsXL#1007]
**Description**

Generally I set keepInventoryOn enter, finish, leave, escape and death.
But sometimes when people die, error popup with my DXL then people lost their equipment.

**Reproduce**

It happens only when player raids as groups, but it happens randomly when player dies, random players, both my dungeons, created and built at SNAPSHOT 1081.
Unfortunatelly it didn't happen to me any time, and deaths aren't specific, just mobs killed players and they didn't got their equipment back. It didn't happen on my tests, I died a lot of times by multiple reasons, but it isn't the case, I don't see pattern at all.

Error which is raised in console when someone die and lost his equipment:

`[10:26:30] [Server thread/ERROR]: Could not save data net.minecraft.server.v1_16_R3.PersistentRaid@699f6f1
java.io.FileNotFoundException: ./DXL_Game_6/data/raids.dat (No such file or directory)
    at java.io.FileOutputStream.open0(Native Method) ~[?:?]
    at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
    at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
    at java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[?:?]
    at net.minecraft.server.v1_16_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:81) ~[patched_1.16.5.jar:git-Paper-505]
    at net.minecraft.server.v1_16_R3.PersistentBase.a(SourceFile:51) ~[patched_1.16.5.jar:git-Paper-505]
    at net.minecraft.server.v1_16_R3.WorldPersistentData.a(WorldPersistentData.java:194) ~[patched_1.16.5.jar:git-Paper-505]
    at net.minecraft.server.v1_16_R3.WorldServer.aj(WorldServer.java:1025) ~[patched_1.16.5.jar:git-Paper-505]
    at net.minecraft.server.v1_16_R3.WorldServer.saveData(WorldServer.java:1019) ~[patched_1.16.5.jar:git-Paper-505]
    at net.minecraft.server.v1_16_R3.WorldServer.saveIncrementally(WorldServer.java:967) ~[patched_1.16.5.jar:git-Paper-505]
    at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-505]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-505]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-505]
    at java.lang.Thread.run(Thread.java:834) [?:?]
    [10:26:30] [Server thread/ERROR]: Failed to save level ./DXL_Game_6
java.io.IOException: No such file or directory
    at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:?]
    at java.io.File.createTempFile(File.java:2092) ~[?:?]
    at net.minecraft.server.v1_16_R3.Convertable$ConversionSession.a(Convertable.java:303) ~[patched_1.16.5.jar:git-Paper-505]
    at net.minecraft.server.v1_16_R3.WorldServer.saveIncrementally(WorldServer.java:982) ~[patched_1.16.5.jar:git-Paper-505]
    at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-505]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-505]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-505]
    at java.lang.Thread.run(Thread.java:834) [?:?]`

**Expected behavior**

In following configuration, my players inventory shouldn't be lost when they die. It causes me a loot of trouble to backup their equipment, and twice of that to chech if their got these items. 
Generally when something like that happens, dxl should make backup copy of player equipment - possible to regive with command in case of any future error. But in the best case that error shouldn't raise.

**Screenshots / GIFs / videos**

Not aplicable

**Relevant configuration files**

Floor configuration:
```
timeUntilKickOfflinePlayer: 0
fly: false
requirements:
  groupSize:
    minimum: 1
    maximum: 3
  forbiddenItems:
    - CHORUS_FRUIT
    - ELYTRA
    - SHULKER
    - ENCHANTED_GOLDEN_APPLE
  keyItems:
    - GOLD_BLOCK
keepInventoryOnEnter: true
keepInventoryOnFinish: true
keepInventoryOnLeave: true
keepInventoryOnEscape: true
keepInventoryOnDeath: true
timeToNextPlayAfterStart: 1
timeToNextPlayAfterFinish: 3
timeToNextLoot: 3
fly: false
friendlyFire: false
gameCommandWhitelist:
  - helpop
  - msg
initialLives: 2
breakBlocks: true
breakWhitelist:
  COBWEB: []
time: 5000
```

Plugin configuration:
```
configVersion: 20
language: english
enableEconomy: true
groupAdaptersEnabled: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
editInstanceRemovalDelay: 5
strictMovementCheckEnabled: true
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
  editCommandWhitelist:
    - setwarp
    - warps
    - warp
    - msg
    - tempban
    - mute
    - /pos1
    - /pos2
    - /copy
    - /paste
    - /rotate
    - /undo
    - /replace
    - /set
    - /fixwater
    - /fixlava
    - /wand
    - /expand
    - /replace
    - /set
    - /fill
    - /sphere
    - /hsphere
    - /faces
    - /walls
    - /cyl
    - /hcyl
    - speed
    - /br
    - mask
    - tp
    - tpa
    - tpaccept
    - tpcancel
    - socialspy
    - day
    - night
    - invsee
  
backupMode: ON_DISABLE_AND_SAVE
lobbyContainersEnabled: true
default: {}
```

If I should share something more, please tell me, but generally this error is always the same for both dungeons with only DXL_Game number changed. If necessary, 

I'm using following features of DXL:
[Checkpoint], [mob] (mythic mobs), [leave], [start] Adventure, [lobby] and distance based triggers.
I can attach dungeons maps if necessary, but when it happens everywhere maybe it could be possible to reproduce.
