### ISSUE TITLE
Allow players to break all blocks?

### ISSUE THREAD

**Issue by markdude701** [DRE2N/DungeonsXL#1041]
**The feature you'd like to know more about**
Floor configuration config -> breakBlocks

**Additional Info**
Hi Folks. Great plugin and thank you for all work you do! 

I'm running into an issue getting my config working how I would like and hope to get some insight. We would like to allow all players to break any block in a dungeon map. From my understanding, game rules do not exist anymore. The config for this is a floor configuration in [my_server]\plugins\DungeonsXL\maps\ [my_dungeon_name]\config.yml. 

I'm an OP on my server, so that should eliminate build permissions/another plugin as a potential issue. Additionally, the buildWhitelist should not work if this was the case but it is working as expected. I would just like to expand this whitelist to all blocks and tools, without having to whitelist each item/block individually. 

I've tried a handful of items (listed below) but I feel I am missing something simple here. Any insight would be greatly appreciated! 

**Link to the wiki article (in case it exists)**
- https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration 

**What did you already try?**
1. Copy and paste the example config. Adjusted values for my server. 
1.(a) Only added "Game Rules" section config initially. Then also added "Map-Specific Rules" to floor config. 
2. Used http://yamllint.com to verify yml file. 
3. Removed break and place whitelist. Players can now place and break their own blocks, not break the world's blocks/items. 
4. Removed any additional unnecessary configs
5. Readded break whitelist to test. Players could break blocks the specified tools and blocks in the whitelist. (Still unable to break other blocks not specified in the whitelist (as expected)). 
6. Adjusted config in reference to https://github.com/DRE2N/DungeonsXL/issues/219 - Omitting the place whitelist, again, players can break placed blocks, but cannot break map blocks. 

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```
**Map config:**
escapeLocation: "spigot_world,-6.0,87.0,-258.0,-110.0,0.0"
finishLocation: "spigot_world,-6.0,87.0,-258.0,-110.0,0.0"
initialLives: 3
invitedPlayers: 
  - markdude701
  - Sir_Sleeves
  - aec08bd2-92b2-4a7a-9f22-8061292d9d04
keepInventoryOnDeath: false
keepInventoryOnEnter: true
keepInventoryOnEscape: true
keepInventoryOnFinish: true
placeBlocks: true
breakBlocks: true
breakPlacedBlocks: true
time: 20000


**plugin config:**
configVersion: 20
language: english
enableEconomy: false
groupAdaptersEnabled: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
editInstanceRemovalDelay: 5
strictMovementCheckEnabled: true
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
lobbyContainersEnabled: false
default:
  damageProtectedEntities:
  - ARMOR_STAND
  - ITEM_FRAME
  - PAINTING
  interactionProtectedEntities:
  - ARMOR_STAND
  - ITEM_FRAME
```
edit: formatting, wording
