### ISSUE TITLE
It doesn't saves the changes I do on /dxl edit 

### ISSUE THREAD

**Issue by balbino-cpu** [DRE2N/DungeonsXL#1058]
**Description**
When I do /dxl edit and I edit the dungeon and do /dxl save it says "Map saved" but when I play it the changes aren't saved

**Reproduce**
1. Create a Dungeon
2. Save it
3. Do /dxl edit to edit it
4. Do the changes you want
5. Do /dxl save to save it (I alredy tried to only do /dxl leave and save it automatically but doesn't work)
6. It says "Map Saved"
7. Play it, the changes arent there

**Expected behavior**
It's expected to save the changes

**Relevant configuration files**

Main config.yml:

```
configVersion: 20
language: english
enableEconomy: false
groupAdaptersEnabled: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
editInstanceRemovalDelay: 5
strictMovementCheckEnabled: true
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
lobbyContainersEnabled: false
default:
  damageProtectedEntities:
  - ARMOR_STAND
  - ITEM_FRAME
  - PAINTING
  interactionProtectedEntities:
  - ARMOR_STAND
  - ITEM_FRAME
```

```

Dungeon config.yml
```
timeUntilKickOfflinePlayer: 120

timeToNextPlayAfterStart: 1

# Shall players play the dungeon with their own items or do you want to use classes?
keepInventoryOnEnter: true
# Shall players lose their items when they die (do not mix up this with "onEscape"!)?
keepInventoryOnDeath: true
# Shall players keep their inventory when they finish the dungeon?
keepInventoryOnFinish: true
# Shall players keep their inventory when they leave the dungeon without succeeding?
keepInventoryOnEscape: false
```
