### ISSUE TITLE
Teleportation not working

### ISSUE THREAD

**Issue by doctorblanket** [DRE2N/DungeonsXL#1098]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**
Teleport signs or trigger signs dont work at all. here's the error from the console: https://mcpaste.io/2c8b90d5ae4ea9a2
(A clear and concise description of what the bug is, e.g.:
Every time my mob signs spawn pigs, they turn green and fly away.)

**Reproduce**
even in a new dungeon they don't work: https://mcpaste.io/d29c63ee1195ce52
(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Place [ready] sign, [mob]/pig/0,1/D5 sign
3. Leave edit mode with /dxl leave
4. Test with /dxl play
5. Trigger ready sign and get close to the location of the pig spawn sign)

**Expected behavior**
the player is teleported when interacting with the button that is on the block that the trigger sign is attached to
(A clear and concise description of what you expected to happen, e.g.:
I wanted the pigs to turn blue and dig mole-like tunnels instead X( )

**Screenshots / GIFs / videos**

(If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```
configVersion: 20
language: english
enableEconomy: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: false
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
default: {}
groupAdaptersEnabled: false
editInstanceRemovalDelay: 5
strictMovementCheckEnabled: true
lobbyContainersEnabled: false

```
