### ISSUE TITLE
Inventories?

### ISSUE THREAD

**Issue by Finalaoh** [DRE2N/DungeonsXL#194]
So we recently installed DungeonsXL on our server, and upon going into a lobby for a game, the players inventory is cleared, and doesnt transfer over from the main world. Worse, upon completing the dungeon, the player does not get their original inventory back. Help?

**Comment by Sataniel98** [comment]
You should have a look at the FAQ and the game rule system, especially the keepInventory rules ;)

**Comment by Finalaoh** [comment]
Gamerules don't apply here. That's not the issue

**Comment by Sataniel98** [comment]
Yes they do. By default, keepInventoryOnEnter is false, so you will of course not be able to take your stuff with you.

**Comment by Finalaoh** [comment]
I had a derp. Game rules to me are the MC default ones. 

Now here's the second question, I added them to my overall config.yml file. Is that the correct thing to do? Or do I need to make a new config.yml per map folder?

**Comment by Sataniel98** [comment]
The values in the default section of the main config apply to all dungeons and floors, while the floor config values override the main config defaults if they are specified.

**Comment by Finalaoh** [comment]
So if I copy said Gamerules into mainconfig, it should apply to all future
maps and current maps?

**Comment by Sataniel98** [comment]
Yes

**Comment by Finalaoh** [comment]
So I have added each gamerule value to my main Config. Upon entering a dungeon, my items are removed still, and when I exit, I have no items, including my gear from entering. Am I retarded? Most likely, but any insight?

**Comment by Sataniel98** [comment]
I can't help you without your configs.

**Comment by Finalaoh** [comment]
```
configVersion: 13
language: english
enableEconomy: false
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- WHITE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
announcementInterval: 30.0
keepInventoryOnEnter: true
keepInventoryOnDeath: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true
sendFloorTitle: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
tweaksEnabled: false
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
  editCommandWhitelist: []
backupMode: ON_DISABLE_AND_SAVE
editPermissions: []
default: {}
```
