### ISSUE TITLE
Dungeon build & Wave problem.

### ISSUE THREAD

**Issue by Ecilpse** [DRE2N/DungeonsXL#219]
[config.zip](https://github.com/DRE2N/DungeonsXL/files/828927/config.zip)

Hi. Thanks for the previous response. I have few more questions to ask after further progress:
1. I would like to create a resource collecting system with a another plugin
(OtherDrops/link: https://dev.bukkit.org/projects/otherdrops)
that allows the game to drop a specific (customized data)block
upon the block destruction within a DXL dungeon.
However, when I had my 'Build:' value as true in my config.yml,
any blocks could not be destroyed or be built in any gamemodes while playing the dungeon.
When I tried the block build-destroy setting, I only had DXL(), multiworld, essentials and mythicmobs plugin in my server. (ofc I used the latest DXL build. - 0.15.7-SNAPSHOT-08)
Config.yml was working properly since the title change I made in the config.yml also appeared in the dungeon play.
Please check if this 'build:' section is working properly, and let us know what can we do to fix this.
(Also, when I searched for the name of the DXL game world in order to make my resource collecting system, I found the name DXL_Game_2. Is this the proper name of the world?)
I will include my config.yml for the reference so you can check.

2. I had a problem figuring out the details of the wave sign.
you said the second line (mob increase rate) can increase the amount of mobs that spawn with a multiplier, and it is supposed to be used with the W (wave) trigger.
However, whenever I could not find any way to limit the # of the waves a wave sign can produce. Please let us know if this is possible.

**Comment by Sataniel98** [comment]
1. Sorry, my bad... Just realized that I forgot to update the documentation after I reworked the building feature. To make it short, the "build" gamerule does not exist anymore. It has been replaced with:
```
# If players can build and destroy blocks in this world.
breakBlocks: true
# CURRENTLY UNUSED
# A whitelist of breakable blocks.
# breakBlocks is supposed to be set to "true" if this should be used.
breakWhiteList:
  # A material value and a list of all tools that can destroy this block
  SPONGE: ["IRON_PICKAXE", "STICK"]
  # Dirt blocks can be destroyed with any tool
  DIRT: []
placeBlocks: true
# A whitelist of placeable blocks.
# placeBlocks is supposed to be set to "true" if this should be used.
placeWhitelist:
  - SPONGE
```

2. Wave signs should make new waves until a progress trigger intervenes. Well yeah, I'm always open for suggestions to make this monstro simile at least a bit easier to use. If you have any good ideas to redesign the wave system, please feel free to tell me about it.
