### ISSUE TITLE
Signs localization

### ISSUE THREAD

**Issue by WillPowerCraft** [DRE2N/DungeonsXL#228]
how about give us to edit signs?

i have plugin on main server for regions AreaShop
that give me way to edit all signs used by plugin like i need:

for example that part of .yml file:

```
##### Set the layout and functions of the signs.
  # The following sections can be added for performing certain commands when the sign is clicked:
  #     rightClickPlayer, rightClickConsole, shiftRightClickPlayer, shiftRightClickConsole,
  #     leftClickPlayer, leftClickConsole, shiftLeftClickPlayer, shiftLeftClickConsole.
  # Sections with 'Player' at the end will be run by the player that clicks the sign and 'Console' ones from the console.
  signProfile:
    forrent:
      line1: '&2&l[For Rent]'
      line2: '%region%'
      line3: '%duration%'
      line4: '%price%'
      rightClickPlayer:
        - 'areashop rent %region%'
      rightClickConsole:
      #  - 'areashop message %clicker% %lang:confirm-rent|%region%|%' # Alternative to first ask for confirmation (remove rightClickPlayer section)
      leftClickPlayer:
        - 'areashop info region %region%'
```

I hope ure add that option in nearest update ^_^
