### ISSUE TITLE
Reward Problem

### ISSUE THREAD

**Issue by iamadcat** [DRE2N/DungeonsXL#281]
@Sataniel98 hmm i did and i made a chest. i wrote sign [Chest] / 150,2 / test
but it keeps saying like this.

![20170607003115](https://user-images.githubusercontent.com/16010851/26863964-965462a2-4b90-11e7-8a3a-fa6a2ae6b122.png)

loot table for test

test.yaml

```
0:
  # For more information about the Caliburn item serialization format,
  # please have a look at the Caliburn wiki:
  # https://github.com/DRE2N/CaliburnAPI/wiki/Custom-item-script
  item:
    ==: io.github.dre2n.caliburn.item.UniversalItemStack
    type: "CUSTOM_DEFAULT"
    material: "IRON_SWORD"
    durability: 35
    name: "&4CustomName"
    amount: 1
    lores:
     - "&4This is the first line."
     - "&6This is the second line."
    enchantments:
      "PROTECTION_ENVIRONMENTAL": 4
      "THORNS": 1
    attributes:
      name:
        type: "GENERIC_ATTACK_DAMAGE"
        slots:
          - "MAIN_HAND"
          - "HEAD"
        operation: "ADD_NUMBER"
        amount: 8.5
  # The loot chance in percent
  chance: 100.0

1:
  # This is the simple way to store items.
  # Valid input:
  # The first value may be any ID (be it a Vanilla ID or an ID of an ItemsXL item), 
  # the second value is the amount
  # and the third, optional value is the durability value.
  item: "261,1,16"
  chance: 100.0

2:
  # The Caliburn API also supports the usual Bukkit ItemStack deserialization format.
  # If you don't know how to use this and have ItemsXL installed,
  # put the item stack into your main hand and enter the "/ixl serialize" command.
  # You will find a valid, automatically generated YAML representation of your item
  # in the ItemsXL/serialized.yml file.
  item:
    ==: org.bukkit.inventory.ItemStack
    type: IRON_SWORD
    damage: 55
    amount: 1
  chance: 37.5
```
