### ISSUE TITLE
Requirements not fulfilled even if there are none

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#309]
Default players can't click the ready sign because of: "You don't fulifll the requirements blabla", still in that dungeon config.yml the requirements section is empty. Still, as OP, I can do that

```
# Floor configuration of DungeonsXL (config.yml in DungeonsXL/map/%mapName% folder)

# You can force a game type sothat the game type defined by a ready sign gets overriden.
forcedGameType: DEFAULT

# If the Lobby is disabled. This applies only to Dungeons that have to be solved alone and where there are no classes to choose from.
isLobbyDisabled: false

# Time until a player is kicked from a dungeon after going offline (in seconds)
# -1 = never / 0 = immediately
timeUntilKickOfflinePlayer: 60

#The game mode, SURVIVAL if nothing
gameMode: ADVENTURE

# PvP
playerVersusPlayer: false
# Friendly fire refers just to members of the same group
friendlyFire: false

# These commands can be used by all players if they are in the dungeon.
# DXL commands like /dxl leave are included by default.
gameCommandWhitelist:
  - version

# MAKE SURE YOU EDIT THIS PART!
# One of these Dungeons must be finished ("any" for any dungeon). If you do not want any, leave this empty.
mustFinishOne:
  - any

# All of these Dungeons must be finished. If you do not want any, leave this empty.
mustFinishAll:

# Shall players play the dungeon with their own items or do you want to use classes?
keepInventoryOnEnter: true
# Shall players lose their items when they die (do not mix up this with "onEscape"!)?
keepInventoryOnDeath: true
# Shall players keep their inventory when they finish the dungeon?
keepInventoryOnFinish: true
# Shall players keep their inventory when they leave the dungeon without succeeding?
keepInventoryOnEscape: true

# If players can build and destroy blocks in this world.
breakBlocks: false
# CURRENTLY UNUSED
# A whitelist of breakable blocks.
# breakBlocks is supposed to be set to "true" if this should be used.
breakWhiteList:
placeBlocks: false
# A whitelist of placeable blocks.
# placeBlocks is supposed to be set to "true" if this should be used.

# Amount of lives a player initially has when he enters a dungeon
initialLives: 2

# Messages also to be created with /dxl msg
message:
  '1': Welcome to this dungeon!

# Items you cannot drop or destroy
secureObjects:
- 69

requirements:
  # If the group has too many or not enough members, the players will not be allowed to use the ready sign.
  groupSize:
    minimum: 1
    maximum: 2
  # Players must have these permission nodes to enter the dungeon:
  permission:

# Use this to replace the default ready / new floor message.
# This is fully compatible with the override system.
# If titles are deactivated in the main config, this is not going to work.
title:
  title: "&4Laboratory"
  subtitle: "&6Help Ytnoos find his badge"
  actionBar: "&aLv.0"
  #chat: "&bmessaggio"
  # How long shall the title be visible (seconds)?
  # The title works without these three options.
  fadeIn: 1.0
  show: 5.0
  fadeOut: 1.0
```

Before there was no "requirements" section at all, but still nothing.
I have no options set about permissions in the main config.yml
