### ISSUE TITLE
LootTables Issue

### ISSUE THREAD

**Issue by PeonFlamo** [DRE2N/DungeonsXL#349]
Hi, so I am trying to setup a loot table but I think I might be doing something wrong. Essentially what I'm trying to do is give people a piece of paper with a custom name that they can use as a token for something unrelated. Here is my current .yml in the scripts/loottable folder:

0:
  item:
    ==: org.bukkit.inventory.ItemStack
    type: PAPER
    name: "&a&l&nCOMMON §8§l§nToken"
    amount: 1
    lores:
     - "§7Throw this token into the token trading place"
     - "§7at spawn to recieve a §8§l§nA Lost §a§l§nCommon§8§l§n Book."
  chance: 100

--The tabs aren't working like how they are in the .yml, according to http://www.yamllint.com/ it is valid in the .yml--

So what is happening is that the chest does give the paper, however in chat (when they click the chest) "1 paper have been added to your reward inventory!" I assume at that point it should be displaying the custom name ("COMMON Token") and once they end the dungeon it is just called Paper. Reason I need it to have the custom name is because they throw the paper into a dropper and receive a custom enchantment book from a separate addon. I did try to just make it so they get the book straight up but couldn't work that out so I just went with this token system.

Any help is appreciated :)

**Comment by Sataniel98** [comment]
"name" isn't Bukkit's identifier for item names. As far as I know, it should be "displayName", but I'm not entirely sure. If you use ItemsXL, you can use /ixl serialize to get the exact format automatically.

**Comment by PeonFlamo** [comment]
So ItemsXL gave me:

serialized:
  ==: org.bukkit.inventory.ItemStack
  type: PAPER
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §a§l§nCOMMON §8§l§nToken
    lore:
    - §7Throw this token into the token trading place
    - §7at spawn to recieve a §8§l§nA Lost §a§l§nCommon§8§l§n Book.

--Again, tabs aren't displaying.--

When I go into the dungeon, click on a chest, all that happens now is " have been added to your reward inventory!" Upon finishing the dungeon and doing /dxl rewards it has no items. I also tried changing the "serialized:" to "items:" but I got the same result. Here are a few screenshots:
![chestsetup](https://user-images.githubusercontent.com/35565465/35111509-2c69c95c-fcc7-11e7-80be-5e418d5d0902.png)
![chatannoucement](https://user-images.githubusercontent.com/35565465/35111518-3020fa2a-fcc7-11e7-9096-0d7a0766d008.png)
![treasuregui](https://user-images.githubusercontent.com/35565465/35111526-375fee4a-fcc7-11e7-995d-37e632260b46.png)

**Comment by PeonFlamo** [comment]
I also just tried putting "" around the display-name: and lore: (was §a§l§nCOMMON §8§l§nToken changed to  "§a§l§nCOMMON §8§l§nToken")

**Comment by Sataniel98** [comment]
IXL won't give you DungeonsXL loot tables of course. You still need to add it to your script correctly and to take care of indents.
```
0:
  item:
    ==: org.bukkit.inventory.ItemStack
    type: PAPER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §a§l§nCOMMON §8§l§nToken
      lore:
      - §7Throw this token into the token trading place
      - §7at spawn to recieve a §8§l§nA Lost §a§l§nCommon§8§l§n Book.
  chance: 50.0
```

**Comment by PeonFlamo** [comment]
I changed it to the following:
```
0:
  item:
    ==: org.bukkit.inventory.ItemStack
    type: PAPER
    display-name: "§a§l§nCOMMON §8§l§nToken"
    amount: 1
    lores:
    - "§7Throw this token into the token trading place"
    - "§7at spawn to recieve a §8§l§nA Lost §a§l§nCommon§8§l§n Book."
  chance: 100
```
Still getting the same issue, I might of missed something however. What it does now is: "1 Paper have been added to your reward inventory!" and the reward GUI has a normal paper in it. Like I said, I might of missed something in it if you happen to notice what. I also tried changing display-name: to displayName, didn't change anything though.
