### ISSUE TITLE
You can only enter this dungeon every 0 hours!

### ISSUE THREAD

**Issue by k-jiang** [DRE2N/DungeonsXL#397]
`You can only enter this dungeon every 0 hours!` when right-click on a `READY` sign.
This prevent ALL players from playing any dungeon games. Yet players have no problem to choose a `classes`.

Server info:
[PaperSpigot](https://ci.destroystokyo.com/job/Paper/) 1.12.2 build 1416
DungeonXL v0.16-SNAPSHOT-612
ItemsXL 0.2.5
MythicMobs 4.3.2
Vault 1.5.6

No errors logged when starting the server.

Notice that this server is located in China with Chinese Standard Time Zone (CST = GMT+8).
We have tried to removed all files under `plugins/DungeonsXL/players/` but it doesn't help.

We don't want to downgrade the DungeonsXL plugins because lower versions contains too many bugs (like #373 ).

I understand that DungeonsXL is a huge project and you guys have been working very hard on it. But we would like to see it fixed. Thank you so much for your efforts!

If you need more info please let me know.

Here is one of the dungeon's config.yml (Player has `betonquest.cooldown.dxl.money01.allow` permission already. It is a custom permission that we make.) :
```
# Floor configuration of DungeonsXL (config.yml in DungeonsXL/map/%mapName% folder)

#########################
# MAP SPECIFIC SETTINGS #
#########################

# Defines the map environment, as this is not saved in the map itself.
# May be set to either THE_END, NETHER or NORMAL.
# If this setting is left out (or if no floor config is used at all), NORMAL will be used.
worldEnvironment: NORMAL
# You can force a game type sothat the game type defined by a ready sign gets overriden.
forcedGameType: PvE Limited

# Players who can to edit the Dungeon (/dxl invite)
# You can add both UUIDs and names.
invitedPlayers:
  - bean
  - babai0
  - duck051314
  - kjiang
  - mashal1004

##############
# GAME RULES #
##############

# If the Lobby is disabled. This applies only to Dungeons that have to be solved
# alone and where there are no classes to choose from.
isLobbyDisabled: false

# Time until a player is kicked from this dungeon after going offline (in seconds)
# -1 = never / 0 = immediately
timeUntilKickOfflinePlayer: 600

# Time in hours until a player can play this dungeon again
# This prevents players from playing the dungeon again if they started the dungeon,
# no matter if they finished, left it or got kicked.
#timeToNextPlayAfterStart: 0

# This only prevents players from playing the dungeon again if they finished it correctly.
# If they leave it or get kicked, players can always retry a dungeon.
#timeToNextPlayAfterFinish: 0

# Time until a player can get loot for another time
timeToNextLoot: 12

# Time until a new mob waves begins when enough mobs are killed.
timeToNextWave: 10

# Dungeons can be played with a timer.
# If the group has no time left, the players get kicked.
timeToFinish: 14400

#The game mode, SURVIVAL if nothing
gameMode: SURVIVAL

# PvP
playerVersusPlayer: false
# Friendly fire refers just to members of the same group
friendlyFire: false

# These commands can be used by all players if they are in the dungeon.
# DXL commands like /dxl leave are included by default.
gameCommandWhitelist:
  - version
  - f list
  - f show
  - ch global

# MAKE SURE YOU EDIT THIS PART!
# One of these Dungeons must be finished ("any" for any dungeon).
# If you do not want any, leave this empty.
mustFinishOne: []
#  - survival_dungeon_xxx
#  - survival_dungeon_yyy

# All of these Dungeons must be finished. If you do not want any, leave this empty.
mustFinishAll: []
#  - survival_dungeon_aaa
#  - survival_dungeon_bbb

# Max time in hours after the last finish of one of the Dungeons above
timeLastPlayed: 0

# A list of requirements
# Note that requirements will be ignored if the player has the
# dxl.ignorerequirements permission node.
requirements:
  feeMoney: 0
  feeLevel: 0
  # If the group has too many or not enough members, the players will not be allowed to use the ready sign.
  groupSize:
    minimum: 1
    maximum: 3
  # Players must have these permission nodes to enter the dungeon:
  permission:
    - betonquest.cooldown.dxl.money01.allow

# Shall players play the dungeon with their own items or do you want to use classes?
keepInventoryOnEnter: false
# Shall players lose their items when they die (do not mix up this with "onEscape"!)?
keepInventoryOnDeath: true
# Shall players keep their inventory when they finish the dungeon?
keepInventoryOnFinish: false
# Shall players keep their inventory when they leave the dungeon without succeeding?
keepInventoryOnEscape: false

# If players can build and destroy blocks in this world.
breakBlocks: false
# If players may destroy blocks they placed themselves.
breakPlacedBlocks: false
# A whitelist of breakable blocks.
# breakBlocks is supposed to be set to "true" if this should be used.
breakWhitelist:
  # A material value and a list of all tools that can destroy this block
  SPONGE: ["GOLD_SPADE", "GOLD_HOE"]
  # Furnace blocks can be destroyed with any tool
  FURNACE: []

# A list of all entity types that shall be protected from damage.
# If this is left out AND if breakBlocks is false, armor stands, paintings
# and item frames will be protected by default.
# If this is left out and if breakBlocks is true, nothing will be protected by default.
damageProtectedEntities: []
# A list of all entity types
# If this is left out AND if breakBlocks is false, armor stands
# and item frames will be protected by default.
# If this is left out and if breakBlocks is true, nothing will be protected by default.
interactionProtectedEntities:
  - ARMOR_STAND
  - ITEM_FRAME

placeBlocks: false
# A whitelist of placeable blocks.
# placeBlocks is supposed to be set to "true" if this should be used.
placeWhitelist: []
#  - SPONGE
#  - ENDER_PORTAL_FRAME
# Amount of lives a player initially has when he enters a dungeon
initialLives: 5
# Alternatively, you can use group lives.
#initialGroupLives: 5

# Messages also to be created with /dxl msg
message:
  '1': Welcome to this dungeon!
  '2': Another message

# Items you cannot drop or destroy
secureObjects: []

# A list of permissions players get while they play the game.
# The permissions get removed as soon as the player leaves the game.
# Requires Vault and a permissions plugin like PermissionsEx.
gamePermissions: []
#  - dxl.reload
#  - another.node

# Use this to replace the default ready / new floor message.
# This is fully compatible with the override system.
# If titles are deactivated in the main config, this is not going to work.
title:
  title: "&4金币副本"
  subtitle: "&6随便服务器专用副本"
  actionBar: "&a作者：玛莎 八百 鸭鸭"
  chat: "&b祝你闯关成功！"
  # How long shall the title be visible (seconds)?
  # The title works without these three options.
  fadeIn: 1.0
  show: 5.0
  fadeOut: 1.0

# If it should rain permanently in the dungeon
# true = permanent rain
# false = permanent sun
# leaving this out = random weather like in vanilla Minecraft
rain: false

# Same principle as above but for thunderstorms
thunder: false

# The time ticks (to be used like in the vanilla /time command)
time: 20000
```

config.yml:
```
configVersion: 15
language: chinese
enableEconomy: false
chatEnabled: true
chatFormatGame: '&2[Game] %group_color%%player_name%: &r'
chatFormatGroup: '&2%group_color%[%group_name%] %player_name%: &r'
chatFormatSpy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- WHITE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
tweaksEnabled: false
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
  editCommandWhitelist: []
backupMode: ON_DISABLE_AND_SAVE
editPermissions: []
default: {}
```
