### ISSUE TITLE
Only one items is add to player inventory when right click on "[Classes]". (What is the new item serialization format?)

### ISSUE THREAD

**Issue by k-jiang** [DRE2N/DungeonsXL#405]
Just tried the build 625 [from here](http://erethon.de/repo/de/erethon/dungeonsxl/). `[Classes]` signs only give me only one item indicated in `scripts/classes/xxx.yml`.

What is the the so called `new item serialization format` actually is? I have tried to convert my classes scripts from Bukkit into Caliburn format with [this](https://github.com/DRE2N/DungeonsXL/wiki/scripts) and [this wiki](https://github.com/DRE2N/CaliburnAPI/wiki/Custom-item-script) but got no luck.

This is what my rewrited scripts looks like:
```
# survival_01_gongshou.yml
items: 
  - 
    ==: de.erethon.caliburn.item.ExItem
    enchantments: 
      ARROW_DAMAGE: 2
      ARROW_INFINITE: 1
      ARROW_KNOCKBACK: 2
      DURABILITY: 3
    lores: 
      - "&4随便服务器专用"
      - "&6金币副本专供"
      - "&9玛莎军火商制造"
    material: BOW
    name: "Cardinal Bow"
    type: DEFAULT
  - 
    ==: de.erethon.caliburn.item.ExItem
    enchantments: 
      DURABILITY: 3
      KNOCKBACK: 4
      SWEEPING_EDGE: 1
    material: IRON_SWORD
    name: "Iron Dagger"
    type: DEFAULT
  - 
    ==: de.erethon.caliburn.item.ExItem
    enchantments: 
      DURABILITY: 3
      PROTECTION_PROJECTILE: 3
    lores: 
      - "&4随便服务器专用"
      - "&6金币副本专供"
      - "&9玛莎军火商制造"
    material: IRON_HELMET
    name: "Witch Hat"
    type: DEFAULT
  - 
    ==: de.erethon.caliburn.item.ExItem
    enchants: 
      DURABILITY: 3
      PROTECTION_ENVIRONMENTAL: 2
      PROTECTION_PROJECTILE: 3
    lores: 
      - "&4随便服务器专用"
      - "&6金币副本专供"
      - "&9玛莎军火商制造"
    material: IRON_CHESTPLATE
    name: "Witch Jacket"
    type: DEFAULT
  - 
    ==: de.erethon.caliburn.item.ExItem
    enchants: 
      DURABILITY: 3
      PROTECTION_ENVIRONMENTAL: 2
      PROTECTION_PROJECTILE: 3
    lores: 
      - "&4随便服务器专用"
      - "&6金币副本专供"
      - "&9玛莎军火商制造"
    material: IRON_LEGGINGS
    name: "Witch Pants"
    type: DEFAULT
  - 
    ==: de.erethon.caliburn.item.ExItem
    enchants: 
      DURABILITY: 3
      PROTECTION_FALL: 4
      PROTECTION_PROJECTILE: 3
    lores: 
      - "&4随便服务器专用"
      - "&6金币副本专供"
      - "&9玛莎军火商制造"
    material: IRON_BOOTS
    name: "Witch Boots"
    type: DEFAULT
  - 
    ==: org.bukkit.inventory.ItemStack
    meta: 
      ==: ItemMeta
      meta-type: POTION
      potion-type: "minecraft:luck"
    type: POTION
  - 400,3
  - 262,64
```

This is another scripts (before rewrites):
```
# survival_01_haiming.yml
items: 
  - ==: org.bukkit.inventory.ItemStack
    type: RAW_FISH
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: 咸鱼剑！
      enchants:
        DAMAGE_ALL: 5
        SWEEPING_EDGE: 3
        DURABILITY: 3
      repair-cost: 7 
    lores:
     - "&4随便服务器专用"
     - "&6金币副本专供"
     - "&9玛莎军火商制造" 
  - ==: org.bukkit.inventory.ItemStack
    type: RAW_FISH
    damage: 1
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: 红鲑鱼之怒！
      enchants:
        DAMAGE_UNDEAD: 4
        FIRE_ASPECT: 2
        LUCK: 3
      repair-cost: 7
    lores:
     - "&4随便服务器专用"
     - "&6金币副本专供"
     - "&9玛莎军火商制造" 
  - ==: org.bukkit.inventory.ItemStack
    type: RAW_FISH
    damage: 3
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: 河豚突刺！
      enchants:
        THORNS: 3
        DAMAGE_ARTHROPODS: 4
        KNOCKBACK: 2
      repair-cost: 7
  - ==: org.bukkit.inventory.ItemStack
    type: RAW_FISH
    damage: 2
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: 欧皇一击！
      enchants:
        KNOCKBACK: 1
        LOOT_BONUS_MOBS: 3
        MENDING: 1
      repair-cost: 7
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      display-name: 海神的祝福！
      potion-type: minecraft:luck
  - ==: org.bukkit.inventory.ItemStack
    type: LEATHER_HELMET
    meta:
      ==: ItemMeta
      meta-type: LEATHER_ARMOR
      display-name: Scarecrow Head
      enchants:
        PROTECTION_FIRE: 3
        OXYGEN: 3
        DURABILITY: 5
        LUCK: 3
      repair-cost: 7
      color:
        ==: Color
        RED: 29
        BLUE: 33
        GREEN: 29
  - ==: org.bukkit.inventory.ItemStack
    type: LEATHER_CHESTPLATE
    meta:
      ==: ItemMeta
      meta-type: LEATHER_ARMOR
      display-name: Scarecrow Shirt
      enchants:
        PROTECTION_ENVIRONMENTAL: 4
        PROTECTION_FIRE: 3
        DURABILITY: 5
        LUCK: 3
      repair-cost: 15
      color:
        ==: Color
        RED: 29
        BLUE: 33
        GREEN: 29
  - ==: org.bukkit.inventory.ItemStack
    type: LEATHER_LEGGINGS
    meta:
      ==: ItemMeta
      meta-type: LEATHER_ARMOR
      display-name: Scarecrow Pants
      enchants:
        PROTECTION_ENVIRONMENTAL: 4
        PROTECTION_FIRE: 3
        DURABILITY: 5
        LUCK: 3
      repair-cost: 15
      color:
        ==: Color
        RED: 29
        BLUE: 33
        GREEN: 29
  - ==: org.bukkit.inventory.ItemStack
    type: LEATHER_BOOTS
    meta:
      ==: ItemMeta
      meta-type: LEATHER_ARMOR
      display-name: Slime Boots
      enchants:
        DEPTH_STRIDER: 3
        PROTECTION_FIRE: 3
        DURABILITY: 5
        LUCK: 3
      repair-cost: 7
      color:
        ==: Color
        RED: 29
        BLUE: 33
        GREEN: 29
  - 282,3
```

Did I do something wrong with the formating? Or is it due to the api under-developments with something not finished yet? Let me know if you need more info.
