### ISSUE TITLE
Group signs stop working on server-restart.

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#513]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
Group-signs work after server-restart

### Actual behavior
If i create a DXL sign in my main world like this:

[DXL]
Group
Crash
3,Crash,3

It works completely fine.
Then i do /dxl reload to store all data and wait until the next auto-server restart.
When i try to use the group sign then it doesnt work. It still is a sign with green color and "Join Group" but it doesnt work anymore.
The signs inside the dungeons work completely well! (Except Wave-Trigger but thats another issue i will open)
I tried 0.17.4 and your 0.17.5 Snapshot. And deleting my complete DXL folder.

### Steps to reproduce
Creating a group sign, reload, wait until restart and try to click it again.
Possbile plugins that cause interference:
-EssentaislX
-WorldEdit
-WorldGuard
-CoreProtect
-ViaVersion
-LuckPerms
-Multiverse-Core
-Vault (possibly not but ill still tell you)

Spigot Version: 1.12.2
Bug Present since: Half year.
I looked on all other Issue_tickets to this Problem but i found no solution, there you said you fixed that in 0.17.4 but it still doesn't work for me!

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
0.17.4 was a hotfix for 1.13.2 support, where group signs among many other things did not work. It did not address the data loss bug. This one has already been described in #447. Thank you anyway for the report, it would really be helpful if you could show me the content of your data.yml file before, after reloading and after reloading for a second time. Are there any stacktraces?

**Comment by ghost** [comment]
Ill send u the data when i got time.
Would other things also be helpful? 
Maybe Server logs and/or running Server with dxl only? I would be happy if i can help, because i think this bug is still present and people won't stop opening issues as long its not fixed! 
(Your Plugin is just Awesome!! But people can't use it on my Server without group signs..)
And what do you mean with stacktrace? I'll just post the whole data.yml here!
I should also be mentioning that the group-sign isn't protected after reload+restart..
Thanks for your help!!!

**Comment by ghost** [comment]
Oh, i just watched into #447.
/dxl reload works completely fine. The Signs still work after dxl reload.
But after the restart they don't work!

**Comment by Sataniel98** [comment]
Thank you! A stacktrace is an error message in the console, that might look similar to this:
```
[(Time) ERROR]: Could not pass event ***Event to DungeonsXL 0.17.4
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute...
Caused by: java.lang.NullPointerException
at de.erethon.dungeonsxl....
```
You should easily be able to find them in your log file by Ctrl+F searching for "at de.erethon.dungeonsxl".

**Comment by ghost** [comment]
[screenlog.txt](https://github.com/DRE2N/DungeonsXL/files/2738189/screenlog.txt)

So, im collecting the data right now:
Data before reloading:
```
configVersion: 2
```
Data after Reload:
```
configVersion: 2
protections:
  groupSigns:
    Spawn:
      '1':
        x: -255
        y: 35
        z: -517
        dungeon: Crash
        maxElements: 3
        startIfElementsAtLeast: 3
        groupName: Crash
  portals:
    Spawn:
      '1':
        loc1:
          x: -252
          y: 34
          z: -526
        loc2:
          x: -249
          y: 36
          z: -526
        material: nether_portal
        axis: x
```
Data after 2nd Reload:
```
configVersion: 2
protections:
  portals:
    Spawn:
      '1':
        loc1:
          x: -252
          y: 34
          z: -526
        loc2:
          x: -249
          y: 36
          z: -526
        material: nether_portal
        axis: x
  groupSigns:
    Spawn:
      '1':
        x: -255
        y: 35
        z: -517
        dungeon: Crash
        maxElements: 3
        groupName: Crash
```
Then i waited about 10 minutes, did /save-all and restarted the server by /stop and starting up again.

After restart the signs DON'T work and the data.yml looks like this:
```
configVersion: 2
protections:
  groupSigns:
    Spawn:
      '1':
        x: -255
        y: 35
        z: -517
        dungeon: Crash
        maxElements: 3
        groupName: Crash
  portals:
    Spawn:
      '1':
        loc1:
          x: -252
          y: 34
          z: -526
        loc2:
          x: -249
          y: 36
          z: -526
        material: nether_portal
        axis: x
```
Then i reloaded the plugin after the restart (sign didn't work so i just reloaded for data catching)
and it looked like this again:
```
configVersion: 2
```

No errors/stacktrace's at all in screenlog.0
only Enable,Loading and checking for Version.
Hope i could help, tell me if you need more data.
