### ISSUE TITLE
Missing reward from loot chest

### ISSUE THREAD

**Issue by Kukkel** [DRE2N/DungeonsXL#520]
Hi! Have seen this issue being asked about twice now, but they got no reply, so might aswell give my contribution.

Tried to create a normal dungeon reward chest. Created a sign to give some money and an enchanted diamond sword.
![sign screenshot](https://user-images.githubusercontent.com/46791593/51337582-27fcc300-1a90-11e9-8f79-94d355e5bb7e.png)

It did give me the money, but only said "have been added to your inventory", when there should've been the sword name at the start of it. Nothing in the reward inventory after exiting the dungeon either.
![screenshot_text](https://user-images.githubusercontent.com/46791593/51337705-81fd8880-1a90-11e9-9323-baf6c9a7e1a4.png)

First got the wiki copy-paste loot table to work, but right after I changed some values, it suddenly started to give this text.

I see nothing wrong with the table either, as all the values are represented, just not the same as wiki example. The table in the folder is, of course, in the .yml format.

[ShinySword.txt](https://github.com/DRE2N/DungeonsXL/files/2769903/ShinySword.txt)

**Comment by Sataniel98** [comment]
Hi,
try http://yamllint.com to validate your YAML syntax.

I haven't tested it, but this should be a correct script:

```
0:
  item: 
    ==: de.erethon.caliburn.item.ExItem
    type: "DEFAULT"
    material: "DIAMOND_SWORD"
    amount: 1
    name: "ShinySword"
    lores:
    - "Shiniest of them all!"
    itemFlags:
    - "HIDE_ATTRIBUTES"
    - "HIDE_ENCHANTS"
    enchantments:
      "SHARPNESS": 3
      "SMITE": 1
    attributes:
      FirstAttribute:
        type: "GENERIC_ATTACK_DAMAGE"
        slots:
        - "MAIN_HAND"
        operation: "ADD_NUMBER"
        amount: 7
  chance: 100.0
```

The errors were that the "FirstAttribute" section lacked the ":" and the usage of TABs instead of spaces, which YAML does not allow.
