### ISSUE TITLE
MFD not working, it doesn't detect my maps

### ISSUE THREAD

**Issue by SpaW2145** [DRE2N/DungeonsXL#572]
I've made an MFD created 12 maps but only start and end floor are detected

```
startFloor: golem_floor_01
floors:
  - golem_floor_02
  - golem_floor_03
  - golem_floor_04
  - golem_floor_05
  - golem_floor_06
  - golem_floor_07
  - golem_floor_08
  - golem_floor_09
  - golem_floor_10
  - golem_floor_11
endFloor: golem_floor_12
floorCount: 8
removeWhenPlayed: false
overrideValues:
  keepInventoryOnEnter: true
  keepInventoryOnFinish: true
  keepInventoryOnEscape: true
  keepInventoryOnDeath: true
configVersion: 1


```
