### ISSUE TITLE
Class scripts question

### ISSUE THREAD

**Issue by fatmanjumprope** [DRE2N/DungeonsXL#573]
**The feature you'd like to know more about**
Using class scripts other than the very basic format. At the moment I can't get any class scripts to work except the very basic formatted ones.

**Link to the wiki article (in case it exists)**
https://github.com/DRE2N/DungeonsXL/wiki/scripts

**What did you already try?**
I have tried numerous different configurations using ItemsXL. Once I upload the scripts into the classes folder inside DXL the plugin seems to accept them. No console errors or messages saying it's formatted incorrectly. However, once in game when someone clicks the sign for the class it will give them no gear. At the moment only the simply storage method for classes actually gives the players gear. I've been wanting to give players enchanted items and such for classes. Below are three of the different configurations I tried with a test item but don't seem to be giving the item. Would you maybe be able to see what I'm doing wrong with these and guide me in the right direction to make them work? 

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
0:
  # For more information about the Caliburn item serialization format,
  # please have a look at the Caliburn wiki:
  # https://github.com/DRE2N/CaliburnAPI/wiki/Custom-item-script
  item:
    ==: de.erethon.caliburn.item.ExItem
    type: "DEFAULT"
    material: "IRON_SWORD"
    amount: 1
    name: "&bBlade Of Lavrål"
    itemFlags:
      - "HIDE_ATTRIBUTES"
      - "HIDE_ENCHANTS"
    enchantments:
      "SWEEPING_EDGE": 2
      "DAMAGE_ALL": 3

serialized:
  ==: org.bukkit.inventory.ItemStack
  v: 1631
  type: IRON_SWORD
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: Blade Of Lavrål
    enchants:
      DAMAGE_ALL: 3
      SWEEPING_EDGE: 2
    itemFlags:
      - "HIDE_ATTRIBUTES"
      - "HIDE_ENCHANTS"

serialized:
  ==: org.bukkit.inventory.ItemStack
  v: 1631
  type: IRON_SWORD
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: Blade Of Lavrål
    enchants:
      DAMAGE_ALL: 3
      SWEEPING_EDGE: 2
    ItemFlags:
    - HIDE_ENCHANTS
    - HIDE_ATTRIBUTES
```

Many thanks!
Fatman

**Comment by Sataniel98** [comment]
Looks like you mixed that up a bit with the loot table script. Take care of the indents and make sure not to copy the "serialized" annotation along with the data. The items of a class are in a list called "items". A list in YAML looks like this:
```
listName:
  - value1
  - value2
  - ...
```
Where a value can have multiple lines.
If the value is an item serialized in the Bukkit format it should end up like this:
```
items:
  - ==: org.bukkit.inventory.ItemStack
    type: IRON_SWORD
    damage: 55
    amount: 1
  - ==: org.bukkit.inventory.ItemStack
    type: IRON_SWORD
    damage: 55
    amount: 1
```
