### ISSUE TITLE
1.13 Items do not work in Dungeon kits.

### ISSUE THREAD

**Issue by philbofett** [DRE2N/DungeonsXL#576]
Hello, I'm just wondering how I am able to get 1.13 items into the dungeon kits, specifically the trident.

This format is the same as any other type of item, besides the fact that it has characteristics such as the enchants that are specific to the trident.
Is this a bug or have I made a mistake somewhere?

```
items:  
  - ==: org.bukkit.inventory.ItemStack
    type: TRIDENT
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: Neptune's Dagger
      enchants:
        IMPALING: 5
        LOYALTY: 2
      repair-cost: 1
      Unbreakable: true
    amount: 1
```
