### ISSUE TITLE
Allowing the breaking of certain blocks

### ISSUE THREAD

**Issue by FunkyJamma** [DRE2N/DungeonsXL#590]
Is there an option to allow the players to break certain blocks? I am able to do this in adventure by generating a pickaxe that will only break a certain type of block. It doesn't seem to work while in game.

**Comment by Sataniel98** [comment]
Have a look at the block breaking game rules:

```
# If players can build and destroy blocks in this world.
breakBlocks: false
# If players may destroy blocks they placed themselves.
breakPlacedBlocks: true
# A whitelist of breakable blocks.
# breakBlocks is supposed to be set to "true" if this should be used.
breakWhitelist:
  # A material value and a list of all tools that can destroy this block
  SPONGE: ["IRON_PICKAXE", "STICK"]
  # Dirt blocks can be destroyed with any tool
  DIRT: []
```

**Comment by FunkyJamma** [comment]
awesome thank you, I went through the configs in the folder I didn't realize I had to create one.

**Comment by FunkyJamma** [comment]
Ok one more issue the documentation says to place it in dungeonsxl/map/mapname

I do not have that directory I have /maps/mapname with an s is this a typo in the documentation or do I need to create new directories?

Floor configuration of DungeonsXL (config.yml in DungeonsXL/map/%mapName% folder)

**Comment by FunkyJamma** [comment]
my config looks like this but it still doesn't allow breaking of blocks. I have also tried both directories from my previous question just in case. 

 If players can build and destroy blocks in this world.
breakBlocks: true
 A whitelist of breakable blocks.
breakBlocks is supposed to be set to "true" if this should be used.
breakWhitelist:
  A material value and a list of all tools that can destroy this block
  SPONGE: ["IRON_PICKAXE", "STICK"]
  Dirt blocks can be destroyed with any tool
  CRACKED_STONE_BRICKS: ["GOLDEN_PICKAXE"]'

**Comment by Sataniel98** [comment]
It was a typo. Make sure to use the custom game type (= no further input on the ready sign) and please use code blocks to show your config sothat I can see if there are any syntax errors. Make sure to use the correct indentation, not to remove the comment symbols (#) and to restart the server.

**Comment by FunkyJamma** [comment]
Not sure I understood the only thing I found was forced game type I set that to default. 

```
--- 
breakBlocks: true
breakWhitelist: 
  CRACKED_STONE_BRICKS: ["GOLDEN_PICKAXE"]
  SPONGE: ["IRON_PICKAXE", "STICK"]
forcedGameType: DEFAULT
```
