### ISSUE TITLE
breakWhitelist doesn't work

### ISSUE THREAD

**Issue by TheRedMajora** [DRE2N/DungeonsXL#623]
**Description**
Mossy Cobblestone isn't breakable with an Iron Pickaxe in my dungeon which is configured for that. 

**Reproduce**
Make a dungeon, set up a pickaxe and some mossy cobble.
Try to mine the cobble

**Expected behavior**
The mossy cobblestone would be mined when using an Iron Pickaxe.

**Relevant configuration files**

config.yml inside the "DungeonsXL/maps/*dungeonname*/" folder
```
damageProtectedEntities:
  - PAINTING
keepInventoryOnDeath: true
breakBlocks: true
breakWhitelist:
  MOSSY_COBBLESTONE: ["IRON_PICKAXE"]
title:
  title: "&4Church of Sin"
  fadeIn: 1.0
  show: 3.0
  fadeOut: 1.0
rain: false
time: 18000
```
Note: The title works fine and there are no error logs, so it can't be the config not being loaded properly?
