### ISSUE TITLE
Why can't place a torch?

### ISSUE THREAD

**Issue by Niinnee** [DRE2N/DungeonsXL#625]
**The feature you'd like to know more about**

[//]: # (e.g. game rules)

**Link to the wiki article (in case it exists)**

**What did you already try?**

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
worldEnvironment: NORMAL
forcedGameType: Custom
isLobbyDisabled: true
timeUntilKickOfflinePlayer: 10000
gameMode: SURVIVAL
requirements:
  groupSize:
    minimum: 2
    maximum: 6
keepInventoryOnEnter: true
keepInventoryOnDeath: false
keepInventoryOnFinish: true
keepInventoryOnEscape: true
gameCommandWhitelist:
 - login
placeBlocks: true
placeWhitelist:
  - torch
```
