### ISSUE TITLE
can't place torch

### ISSUE THREAD

**Issue by Niinnee** [DRE2N/DungeonsXL#626]
**Description**

[//]: # (A clear and concise description of what the bug is.)

**Reproduce**

[//]: # (List steps to reproduce)

**Expected behavior**

[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots / GIFs / videos**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**
![TIM图片20190729232402](https://user-images.githubusercontent.com/30897943/62060746-42da9c00-b258-11e9-911f-ae8d3077e885.png)

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
worldEnvironment: NORMAL
forcedGameType: Custom
isLobbyDisabled: true
timeUntilKickOfflinePlayer: 10000
gameMode: SURVIVAL
requirements:
  groupSize:
    minimum: 2
    maximum: 6
keepInventoryOnEnter: true
keepInventoryOnDeath: false
keepInventoryOnFinish: true
keepInventoryOnEscape: true
gameCommandWhitelist:
 - login
placeBlocks: true
placeWhitelist:
  - torch
initialLives: 0
initialGroupLives: 10
message:
  '1': '&c&l石桥断了.......看来得另找出路了!'
  '2': Another message
title:
  title: '&7&l▒&c&l简单副本&7&l▒'
  subtitle: '&c&l幽暗狼窟'
  fadeIn: 1.0
  show: 3.0
  fadeOut: 1.0
rain: false
thunder: false
time: 20000
secureObjects: []
invitedPlayers: []
```
