### ISSUE TITLE
Can't remove portals

### ISSUE THREAD

**Issue by lenbois** [DRE2N/DungeonsXL#631]
**The feature you'd like to know more about**
Portals. I have no idea how to delete or remove them

**Link to the wiki article (in case it exists)**
None

**What did you already try?**
Deleting them from the yml and restarting the server, replacing the portal

**Relevant configuration files**

```
  portals:
    lenrpg:
      '13':
        loc1:
          x: -337
          y: 61
          z: 513
        loc2:
          x: -335
          y: 57
          z: 513
        material: WATER
      '12':
        loc1:
          x: -337
          y: 61
          z: 513
        loc2:
          x: -335
          y: 57
          z: 513
        material: LAVA
      '11':
        loc1:
          x: -337
          y: 61
          z: 513
        loc2:
          x: -335
          y: 57
          z: 513
        material: NETHER_PORTAL
        axis: x
      '14':
        loc1:
          x: -337
          y: 61
          z: 513
        loc2:
          x: -335
          y: 57
          z: 513
        material: WATER
```
