### ISSUE TITLE
Why does wave sign not work properly

### ISSUE THREAD

**Issue by Niinnee** [DRE2N/DungeonsXL#642]
**Description**

[//]: # (A clear and concise description of what the bug is.)

[MOB]
铜币怪物
2,2,MM
D 100

[WAVE]
1.5
TRUE
W 1

Killing all the monsters won't go into the next round

[//]: # (List steps to reproduce)

**Expected behavior**

[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots / GIFs / videos**
http://www.mediafire.com/file/c8cdiqy507ohv1j/Desktop_2019.08.07_-_21.22.33.01_x264.mp4/file

[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

worldEnvironment: NORMAL
forcedGameType: Custom
isLobbyDisabled: FALSE
timeUntilKickOfflinePlayer: 10000
gameMode: SURVIVAL
requirements:
  groupSize:
    minimum: 1
    maximum: 6
timeToFinish: 240
keepInventoryOnEnter: true
keepInventoryOnDeath: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true
timeToNextWave: 10
gameCommandWhitelist:
 - login
 - rpginv open
initialLives: 1
title:
  title: '&7&l▒&c&l金币副本&7&l▒'
  subtitle: '&c&l金币竞技场'
  fadeIn: 1.0
  show: 3.0
  fadeOut: 1.0
rain: false
thunder: false
time: 8732
secureObjects: []
invitedPlayers: []

```
