### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by maegae** [DRE2N/DungeonsXL#647]
Recently, my dungeons have completely turned off keep inventory, but only partially. When the players die, they drop their items on death, but keep their inventory still, so it duplicates their items. It only started doing this just yesterday
![image](https://user-images.githubusercontent.com/46981076/62989314-595a2900-bdfc-11e9-9fa6-fec377f7a080.png)

First dungeon
```
keepInventoryOnEnter: true
keepInventoryOnDeath: true
keepInventoryOnFinish: true
keepInventoryOnEscape: false
initialLives: 3
timeToNextPlayAfterStart: 1
groupSize:
  minimum: 4
  maximum: 4
title:
  title: '&cFacility'
secureObjects: []
invitedPlayers: []
```
Second Dungeon (same issue)
```
secureObjects: []
keepInventoryOnEnter: true
keepInventoryOnDeath: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true
initialLives: 3
timeToNextPlayAfterStart: 3
title:
  title: '&cDead Mansion'
```
Plugins:
PluginConstructorAPI, PlaceholderAPI, SuperTrailsPro, PlayerRider, OldCombatMechanics, TrollBoss, TreeGravity, F3NPerm, CoreProtect, LuckPerms, WorldEdit, Harbor, OpenInv, MineableSpawners, ItemsXL, Multiverse-Core, ProtocolLib, LibsDisguises, InventoryRollback, AdvancedPortals, UberEnchant, PixelPrinter, Hat, Vault, PlayerParticles, WorldGuard, AuctionHouse, MythicMobs, CustomHeads, Multiverse-NetherPortals, PetMaster, AreaShop, Essentials, DiscordSRV, TradeSystem, WolfyUtilities, EssentialsChat, EmojiChat, RFChairs, SuperVanish, GriefPrevention, ChestShop, DungeonsXL, MythicArtifacts, EssentialsProtect, EssentialsGeoIP, EssentialsAntiBuild, RandomTeleport, DiscordSRV-Staff-Chat, EssentialsSpawn, CustomCrafting
