### ISSUE TITLE
Getting portal msg "You have to join a group first" in non-DXL world at same coordinates

### ISSUE THREAD

**Issue by gmalone** [DRE2N/DungeonsXL#663]
**Description**
[//]: # (A clear and concise description of what the bug is.)
Whenever a player walks over a coordinate location in a non-DXL known world, the message "You have to join a group first!" appears in chat.  It's the same coordinate range as a portal configured in a totally separate DXL world.

**Reproduce**
[//]: # (List steps to reproduce)
Setup a portal in a DXL world.
Go to same coordinates in a non-DXL world.

**Expected behavior**
[//]: # (A clear and concise description of what you expected to happen.)
The message "You have to join a group first!" appears in the non-DXL world's chat whenever walking onto the same coordinates space as in the DXL world that has the porta with those coordinates.

**Screenshots / GIFs / videos**
[//]: # (If applicable, add screenshots to help explain your problem.)
no screenshots required
![DXL-issue](https://user-images.githubusercontent.com/3749543/65391325-2c673300-dd25-11e9-84e5-bc781cbaec33.png)

**Relevant configuration files**
[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)
```
protections:
  portals:
    wochub:
      '1':
        loc1:
          x: -2
          y: 106
          z: -22
        loc2:
          x: 1
          y: 103
          z: -22
        material: NETHER_PORTAL
        axis: x
```
