### ISSUE TITLE
Requirements don't work in the main config

### ISSUE THREAD

**Issue by ParadiddlePride** [DRE2N/DungeonsXL#679]
**Description**
DungeonsXL can no longer load on startup, and produces errors whenever a command is used.
I am currently using Paper for 1.13.2, but I did attempt to switch to Spigot as I heard paper doesn't work well with this plugin. The only difference was that, when running with spigot, it did not disable/produce an error message about disabling.
[//]: # (A clear and concise description of what the bug is.)

**Reproduce**
1) Use latest DXL build
2) Start server
3) Randomly be unable to make it start again
[//]: # (List steps to reproduce)

**Expected behavior**
Plugin should load and not disable itself.
[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots / GIFs / videos**
https://pastebin.com/6dRZixcf
Start up log, as related to the error
[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**
I noticed it mentioned a config, so here's the main DXL config:
[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
configVersion: 16
language: english
enableEconomy: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: false
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
default:
  keepInventoryOnEnter: true
  keepInventoryOnFinish: true
  keepInventoryOnEscape: true
  keepInventoryOnDeath: true
  fly: false
  requirements:  
    forbiddenItems:
      - ELYTRA
  initialLives: 1

```
