### ISSUE TITLE
issue with inventories carrying over

### ISSUE THREAD

**Issue by dgsukinik** [DRE2N/DungeonsXL#714]
**The feature you'd like to know more about**

[//]I am having issues with transferring inventories between dungeons and the base survival world. I am running multiverse, and that is the only other plugin influencing inventories. i am running on 1.14.4

**Link to the wiki article (in case it exists)**

**What did you already try?**
[//] tried messing with the local config

 for the dungeon and the main dungeon config.

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
# Main configuration of DungeonsXL (config.yml in DungeonsXL folder)
# 
# Don't edit this one.
configVersion: 16
language: english
enableEconomy: true
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startgroup: default
  endgroup: player
  startGroup: default
externalMobProviders:
  XY: custommobplugin spawnmob %mob% %world% %x% %y% %z%
  YZ: otherplugincommand summon %mob% %world% %block_x% %block_y% %block_z%
maxInstances: 10
tweaksEnabled: false
secureMode:
  enabled: true
  checkInterval: 5.0
  openInventories: false
  dropItems: false
  editCommandWhitelist:
  - help
  - version
backupMode: ON_DISABLE_AND_SAVE
editPermissions:
- worldedit.clipboard.*
- worldedit.history.*
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
globalDeathMessagesDisabled: false
isLobbyDisabled: false
timeUntilKickOfflinePlayer: 10000
timeToNextPlayAfterStart: 6
timeToNextPlayAfterFinish: 12
timeToNextLoot: 12
timeToNextWave: 10
timeToFinish: 600
gameMode: SURVIVIAL
fly: false
playerVersusPlayer: true
friendlyFire: true
gameCommandWhitelist:
- version
- f list
- f show
- ch global
mustFinishOne: []
mustFinishAll: []
timeLastPlayed: []
requirements:
  feeMoney: 0
  feeLevel: 0
  groupSize:
    minimum: 1
    maximum: 6
  permission: []
  forbiddenItems: []
  keyItems: []
keepInventoryOnEnter: true
keepInventoryOnDeath: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true
breakBlocks: false
breakPlacedBlocks: true
damageProtectedEntities:
- PAINTING
- ARMOR_STAND
interactionProtectedEntities:
- ARMOR_STAND
placeBlocks: true
placeWhitelist: []
initialLives: 3
initialGroupLives: 5
message:
  '1': Welcome to this dungeon!
  '2': Another message
secureObjects: []
gamePermissions: []
title:
  title: '&4Good &4Luck!'
  fadeIn: 1.0
  show: 3.0
  fadeOut: 1.0
rain: true
thunder: true
time: 20000
announcementInterval: 30.0
sendFloorTitle: true
resourcePacks: {}
default: {}

```
