### ISSUE TITLE
[Bug] Players don't fullfill requirements

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#736]
**Description**

When a player try to start dungeon, it says that it doesn't fullfill requirements. 

**Reproduce**

1) Make a dungeon for 3 players
2) Limits to 2-3 players
3) Try to hit ready sign with 2 or 3 players without bypass permission
4) see the messages

**Expected behavior**

Start the dungeon when we fullfill requirments.

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
# Optionally all game rules of a floor config, like:
keepInventoryOnEnter: false
keepInventoryOnDeath: true
keepInventoryOnFinish: false
keepInventoryOnEscape: false
build: false
timeUntilKickOfflinePlayer: 10000
timeToNextPlay: 23
timeToNextLoot: 23
gameMode: ADVENTURE
friendlyFire: false
gameCommandWhitelist:
  - rg flag __global__ ice-melt DENY
  - rtfw
  - time set night
  - time set day
  - psa
  - chairs off
  - journal
  - j
  - backpack
  - class acc 1
  - class acc 2
  - class combo
  - msg
  - r
  - dchat
  - t
  - w
  - dc
  - ag
  - staff
  - menestrel
  - money pay
  - fe send
  - fe
  - money
  - party create
  - party invite
  - party accept
  - party deny
  - party leave
  - party chat
  - party kick
  - kick 
  - crepe
breakBlocks: false
requirements:
# If the group has too many or not enough members, the players will not be allowed to use the ready sign.
  groupSize:
    minimum: 2
    maximum: 3
title:
  title: "&4Arkiverne"
  subtitle: "&6Les archives du monastères"
# How long shall the title be visible (seconds)?
# The title works without these three options.
  fadeIn: 1.0
  show: 3.0
  fadeOut: 1.0
defaultValues:
  # Optionally all game rules of a floor config, like:
  breakBlocks: false
  interactionProtectedEntities: []

```
Build of dungeonsXL #871
