### ISSUE TITLE
Loot drops

### ISSUE THREAD

**Issue by icyvector** [DRE2N/DungeonsXL#791]
**The feature you'd like to know more about**
Loot Scripts
(e.g. game rules)

**Link to the wiki article (in case it exists)**
https://github.com/DRE2N/DungeonsXL/wiki/scripts

**What did you already try?**
I tried creating loot scripts, but I think I set them up wrong. Can anyone see what I did wrong below?

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```
 
item:
    ==: de.erethon.caliburn.item.ExItem
    type: "DEFAULT"
    material: "DIAMOND"
    amount: 2
  # The loot chance in percent
  chance: 5
  
item:
    ==: de.erethon.caliburn.item.ExItem
    type: "DEFAULT"
    material: "IRON_INGOT"
    amount: 5
  # The loot chance in percent
  chance: 50

item:
    ==: de.erethon.caliburn.item.ExItem
    type: "DEFAULT"
    material: "GOLD_INGOT"
    amount: 1
  # The loot chance in percent
  chance: 30
  
item:
    ==: de.erethon.caliburn.item.ExItem
    type: "DEFAULT"
    material: "COAL"
    amount: 1
  # The loot chance in percent
  chance: 100

item:
    ==: de.erethon.caliburn.item.ExItem
    type: "DEFAULT"
    material: "IRON_CHESTPLATE"
    amount: 1
    name: "&4Bandit's Chestplate"
    lores:
     - "&4Forged in lava"
    enchantments:
      "PROTECTION_ENVIRONMENTAL": 3
      "UNBREAKING": 4
  # The loot chance in percent
  chance: 10
```

**Comment by Sataniel98** [comment]
Item and chance aren't on the same level and the items don't have slot IDs:
```
slot:
  item: ...
  chance: ...
```

See also: https://github.com/DRE2N/DungeonsXL/wiki/data-structure-guide

**Comment by IcyVector** [comment]
With the slots do I just name them different variables?

**Comment by icyvector** [comment]
```
0: 
  item:
    ==: de.erethon.caliburn.item.ExItem
    type: "DEFAULT"
    material: "DIAMOND"
    amount: 2
  # The loot chance in percent
  chance: 5
  
1:  
  item:
    ==: de.erethon.caliburn.item.ExItem
    type: "DEFAULT"
    material: "IRON_INGOT"
    amount: 5
  # The loot chance in percent
  chance: 50

2:  
  item:
    ==: de.erethon.caliburn.item.ExItem
    type: "DEFAULT"
    material: "GOLD_INGOT"
    amount: 1
  # The loot chance in percent
  chance: 30
  
3:  
  item:
    ==: de.erethon.caliburn.item.ExItem
    type: "DEFAULT"
    material: "COAL"
    amount: 1
  # The loot chance in percent
  chance: 100

4:  
  item:
    ==: de.erethon.caliburn.item.ExItem
    type: "DEFAULT"
    material: "IRON_CHESTPLATE"
    amount: 1
    name: "&4Bandit's Chestplate"
    lores:
     - "&4Forged in lava"
    enchantments:
      "PROTECTION_ENVIRONMENTAL": 3
      "UNBREAKING": 4
  # The loot chance in percent
  chance: 10
```
Is this the right setup?
