### ISSUE TITLE
[Several Bug] Loss stuff in dungeon (mm)

### ISSUE THREAD

**Issue by Bricec6** [DRE2N/DungeonsXL#838]
**Description**

When I fight against my monster, which is created thanks to mythicmobs, there is a bug and my equipment goes down, but it seems that if you're equipped with helmet, chest protector, leggings, feet the stuff is not dropping.

edit: after tests, no the stuff drops even if you are equipped with a helmet, chest protector, leggings, foot, and even they throw themselves on the ground.
https://www.youtube.com/watch?v=6oHmUSInh8E

If the item drop bug occurred, the instance will have a bug and the monsters will be able to break the map.

**Reproduce**

(List steps to reproduce, e.g.:
1. look a video https://www.youtube.com/watch?v=1pP_ZizR4zc

**Expected behavior**
when the fight takes place, it is possible that the stuff in the inventory and on the player may be sent to the ground for no reason, I checked my mythicmobs boss he doesn't have this ability and anyway it doesn't exist in mythicmobs.

After the player loses his entire inventory, the instance becomes buggy and blocks can be broken, although it's predefined that no

Attention: It seems to me that you only lose your equipment if you don't have a helmet, chest protector, leggings, feet...

**Screenshots / GIFs / videos**
https://www.youtube.com/watch?v=1pP_ZizR4zc  (loss stuff on combat)
https://www.youtube.com/watch?v=9hf1qQzPrOM (block break due to the bug with the loss of stuff)

**Relevant configuration files**

```
# 
# MAP SPECIFIC SETTINGS #
invitedPlayers:
- eadd114a-a63d-401e-ae9f-fb986833c7a7
gameMode: SURVIVAL
fly: false
playerVersusPlayer: false
friendlyFire: false
requirements:
  groupSize:
    minimum: 1
    maximum: 5
  permission:
  - dimension.terra
keepInventoryOnEnter: true
keepInventoryOnDeath: false
keepInventoryOnFinish: true
keepInventoryOnEscape: true
breakBlocks: false
breakPlacedBlocks: false
placeBlocks: false
initialGroupLives: 2
title:
  title: '&fBoss &eEden'
  chat: '&5&lD&5imensions&8 →&7 Pas de retour possible, si vous avez une &fprotection
    &bdivine &7vous ne perdrez pas votre inventaire.'
  fadeIn: 1.0
  show: 3.0
  fadeOut: 1.0
time: 6000

```
