### ISSUE TITLE
Adding Command Reward // CrazyEnchantments Rewards

### ISSUE THREAD

**Issue by cat-boop** [DRE2N/DungeonsXL#840]
**The feature you'd like to know more about**
I am attempting to add custom enchantment books to the rewards chest at the end of my dungeon; I am unable to using a loot table script. I understand I can use a command sign that players click, but this does not fit my needs of adding chances and such. It would be very useful if I could run a command per player once the dungeon END sign has been triggered.
(e.g. game rules)

**Link to the wiki article (in case it exists)**
N/A

**What did you already try?**
N/A

**Relevant configuration files**
N/A 

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```
1:
  # This is the simple way to store items.
  # Valid input:
  # The first value may be any ID (be it a Vanilla ID or an ID of an ItemsXL item), 
  # the second value is the amount
  # and the third, optional value is the durability value.
  item: "264,16"
  chance: 100.0
2:
  item: "388,128"
  chance: 25.0
3:
  item: "266,64"
  chance: 25.0
4:
  item: "264,64"
  chance: 25.0
5:
  item: "130,1"
  chance: 50.0
6:
  item: "381,16"
  chance: 50.0
7:
  item: "399,4"
  chance: 90.0
8:
  item: "381,16"
  chance: 50.0

```

**Comment by Sataniel98** [comment]
You can serialize all items, no matter which plugin created them, with ItemsXL and the /ixl serialize command. The library will soon be updated to a new format though.

**Comment by cat-boop** [comment]
> You can serialize all items, no matter which plugin created them, with ItemsXL and the /ixl serialize command. The library will soon be updated to a new format though.

I appreciate the insanely fast response!

I used your ItemsXL plugin to create this serialized item which is in my DungeonsXL loottable script:
```9:
  item:
  ==: org.bukkit.inventory.ItemStack
  v: 2230
  type: BOOK
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §8§l§nA Lost §4§l§nLegendary§8§l§n Book
    lore:
    - §7This book has been lost for centuries
    - §7It is said to be an enchantment book from §4§l§nLegendary
    - §7But you must clean it off to find out what kind it is.
    - §7§l(§a§l!§7§l) §7Right Click to clean off.
  chance: 100.0```

For some reason it is not appearing in the Reward Inventory at the end of the dungeon. Any idea?

**Comment by Sataniel98** [comment]
The indentation is wrong. The item data must be in the item section. https://github.com/DRE2N/DungeonsXL/wiki/data-structure-guide#yaml

**Comment by cat-boop** [comment]
> The indentation is wrong. The item data must be in the item section. https://github.com/DRE2N/DungeonsXL/wiki/data-structure-guide#yaml

I'm confused? Can you perhaps reformat it properly for me so I can know for the future.

Also just want to thank you so much for makin this awesome plugin, it's been a life saver. :D

**Comment by Sataniel98** [comment]
The syntax is

slot: {item: {==: "org.bukkit.inventory.ItemStack", ...}, chance: 25.0}

What you have is:
slot: {item: null, ==: "org.bukkit.inventory.ItemStack", ..., chance: 100.0}

So it can't recognize the item.

**Comment by cat-boop** [comment]
I don't know if I'm being dumb, but I *attempted* to follow the syntax you provided:

```9:
  item:
  ==: org.bukkit.inventory.ItemStack
  v: 2230
  type: CLOCK
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §4§lDOOM §7Clock
    enchants:
      KNOCKBACK: 3
      DURABILITY: 10
  chance: 100.0```

And it does not appear to be working. :/

**Comment by Sataniel98** [comment]
I used the {} variant (which as valid as the indentations) to highlight what the problem is.

![Unbenannt](https://user-images.githubusercontent.com/8921300/86288761-be706600-bbea-11ea-968a-49f82f9dfe24.png)
```
  item:
  ==: org.bukkit.inventory.ItemStack
    v: 2230
    type: CLOCK
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §4§lDOOM §7Clock
      enchants:
        KNOCKBACK: 3
        DURABILITY: 10
  chance: 100.0
```
