### ISSUE TITLE
Custom mob scripts aren't working on 1.16.1

### ISSUE THREAD

**Issue by kazchan** [DRE2N/DungeonsXL#845]
**Description**
I tried making some custom mob scripts to use inside my dungeon, but they don't seem to be working.

**Reproduce**

1. Below is the script I made, named "skelknight.yml"

```
type: Skeleton
maxHealth: 60
itemHand: 276
itemHelmet: 310
itemChestplate: 311
itemLeggings: 312
itemBoots: 313
isWitherSkeleton: false
drops: 
  1:
    amount: 1
    chance: 20
    enchantments:
      - DAMAGE_ALL 5
      - SWEEPING_EDGE 3
      - DURABILITY 10
    id: 276
    lore: 'An old but durable sword.//Belongs to a former knight.'
    name: 'Knights sword.'
  2:
    id: 310
    amount: 1
    enchantments:
      - PROTECTION_ENVIRONMENTAL 4
      - THORNS 3
      - DURABILITY 10
      # Item name
    name: 'Knights helmet.'
    # Item description (Split multiple lines with '//')
    lore: 'An old but durable helmet.//Belongs to a former knight.'
    # Drop Chance (0-100) (default 100)
    chance: 20
  3:
    id: 311
    amount: 1
    enchantments:
      - PROTECTION_ENVIRONMENTAL 4
      - THORNS 3
      - DURABILITY 10
      # Item name
    name: 'Knights armor.'
    # Item description (Split multiple lines with '//')
    lore: 'An old but durable armor.//Belongs to a former knight.'
    # Drop Chance (0-100) (default 100)
    chance: 20
  4:
    id: 312
    amount: 1
    enchantments:
      - PROTECTION_ENVIRONMENTAL 4
      - THORNS 3
      - DURABILITY 10
      # Item name
    name: 'Knights pants.'
    # Item description (Split multiple lines with '//')
    lore: 'An old but durable pair of pants.//Belongs to a former knight.'
    # Drop Chance (0-100) (default 100)
    chance: 20
  5:
    id: 313
    amount: 1
    enchantments:
      - PROTECTION_ENVIRONMENTAL 4
      - THORNS 3
      - DURABILITY 10
      # Item name
    name: 'Knights greaves.'
    # Item description (Split multiple lines with '//')
    lore: 'An old but durable set of boots.//Belongs to a former knight.'
```

2. The mob sign I used: [mob]/skelknight/0,1/D 15 sign (also put some vanilla mob signs just in case)
3. All reloaded and ready to go.
4. Test with /dxl play
5. Only vanilla mobs are spawning, the custom ones aren't.

Did I get anything wrong? I'm pretty new to these :(.
Thanks.
