### ISSUE TITLE
lava bucket BUG

### ISSUE THREAD

**Issue by Bricec6** [DRE2N/DungeonsXL#865]
**Description**

hello, I've banned the laying of blocks in the dojons but my players can still lay buckets of lava, which blocks my monsters and kills them without difficulty.
I'm not Operator(/op)

**Reproduce**

Video: https://www.youtube.com/watch?v=rV_KLOD1fxs

**Expected behaviour**

If I don't allow block laying, I don't want my players to lay lava in monster fights!

**Screenshots / GIFs / Videos **

Video: https://www.youtube.com/watch?v=rV_KLOD1fxs

**Relevant configuration files**

```
# 
# MAP SPECIFIC SETTINGS #
invitedPlayers:
- eadd114a-a63d-401e-ae9f-fb986833c7a7
gameMode: SURVIVAL
fly: false
playerVersusPlayer: false
friendlyFire: false
finishLocation: "dimensions,334.6,92.0,1875.0"
requirements:
  groupSize:
    minimum: 1
    maximum: 5
  permission:
  - dimension.terra
keepInventoryOnEnter: true
keepInventoryOnDeath: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true
breakBlocks: false
breakPlacedBlocks: true
placeBlocks: false
initialGroupLives: 1
title:
  title: '&fBoss &eEden'
  cat: '&5&lD&5imensions&8 →&7 No returns possible, you don't lose your inventory.'
  fadeIn: 1.0
  show: 3.0
  fadeOut: 1.0
time: 60000

```
