### ISSUE TITLE
Loottable Script

### ISSUE THREAD

**Issue by JUSTCOOP** [DRE2N/DungeonsXL#866]
**The feature you'd like to know more about**
Loottable script

**Link to the wiki article (in case it exists)**
https://github.com/DRE2N/DungeonsXL/wiki/scripts#loot-tables

**What did you already try?**
I tried to add custom item using ItemXL serializing but got nothing. I made a loottable yml (named it common) in scripts folder and pasted code from serialized file. I checked my yml on http://www.yamllint.com and got that's all ok.

**Relevant configuration files**

```
0:
  item:
    ==: org.bukkit.inventory.ItemStack
    v: 2230
    type: WOODEN_SWORD
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §6Деревянный меч
      lore:
      - §9Раньше использовался для
      - §9тренировок рыцарей и
      - §9оруженосцев
      attribute-modifiers:
        GENERIC_MAX_HEALTH:
        - ==: org.bukkit.attribute.AttributeModifier
          amount: 2.0
          name: generic.maxHealth
          slot: HAND
          uuid: 00000000-0000-0063-0000-00000bd71120
          operation: 0
        GENERIC_ATTACK_DAMAGE:
        - ==: org.bukkit.attribute.AttributeModifier
          amount: 4.0
          name: generic.attackDamage
          slot: HAND
          uuid: 00000000-0000-0063-0000-00000bd71184
          operation: 0
      ItemFlags:
      - HIDE_UNBREAKABLE
      - HIDE_POTION_EFFECTS
  chance: 100.0
1:
  item: "261,1,16"
  chance: 100.0
```
