### ISSUE TITLE
Gamerule breakBlocks

### ISSUE THREAD

**Issue by JUSTCOOP** [DRE2N/DungeonsXL#868]
**Description**

I tried to add breakBlocks gamerule but it didn't work.

**Reproduce**

1. Create a new config.yml in map folder
2. Add some rules
3. Checked it
4. All rules worked correctly excluding breakBlocks

**Expected behavior**

I just wanna add posibility to break some blocks in my dungeon using special equipment. I tried to change gamemode to ADVENTURE and to add NBT tags of tools, but it still doesn't work.

**Relevant configuration files**

```
title:
  title: "&4Старое подземелье"
  subtitle: "&bПопытайся выбраться!"
keepInventoryOnEnter: false
keepInventoryOnEscape: false
keepInventoryOnFinish: true
gameMode: SURVIVAL
placeWhitelist:
  - CAKE
placeBlocks: true
initialLives: 3
breakBlocks: true
breakPlacedBlocks: true
breakWhitelist:
  - SPRUCE_LEAVES
  - DIRT
```

**Comment by Sataniel98** [comment]
breakWhitelist is not a list, it's a map of block materials and tools to break them.

```
breakWhitelist:
  # A material value and a list of all tools that can destroy this block
  SPONGE: ["IRON_PICKAXE", "STICK"]
  # Dirt blocks can be destroyed with any tool
  DIRT: []
```
