### ISSUE TITLE
Player Citizen can't be killed

### ISSUE THREAD

**Issue by quentinlegot** [DRE2N/DungeonsXL#874]
**Description**

In dungeons, citizens type player can't be killed (other type like enderman or zombie can)
I tried to activate FriendlyFire and PlayerVersusPlayer but nothing change.
Npcs take damage until sword damage are highter than theirs health, then their health don't decrease

I precise we use Sentinel but npc isn't invincible, moreover, there is'nt exception mesage in console

**Reproduce**

- Create a npc which is type Player and give it sentinel trait
- place it on dungeon thank to sign (I use trigger T to spawn every mob)
- save and play the game
- Try to kill npc

**Expected behavior**

Npc which type Player should be killed

**Screenshots / GIFs / videos**

![image](https://user-images.githubusercontent.com/26069031/89235347-45e83500-d5ee-11ea-935b-be2b97606486.png)

(he can see he have 3.xx hp)

after hitted it three more time(cause it health can regen):
![image](https://user-images.githubusercontent.com/26069031/89235416-687a4e00-d5ee-11ea-9691-a6c696077c5a.png)

**Relevant configuration files**

```
initialLives: 1
friendflyFire: true
playerVersusPlayer: true
requirements:
  permission:
    - dungeon2
time: 9000
rain: false
thunder: false
fireTick: false
title:
  title: Goldmine dungeon
keepInventoryOnEnter: true
keepInventoryOnDeath: true
keepInventoryOnFinish: true
keepInventoryOnEscape: false
```
