### ISSUE TITLE
Keeping Inventory when entering and clearing a dungeon

### ISSUE THREAD

**Issue by Omega7343** [DRE2N/DungeonsXL#880]
**The feature you'd like to know more about**
How does one keep their inventory from the server before they joined the dungeon, and bring it into the dungeon? For example, I want to bring a sword from outside the dungeon into the dungeon, and use with my class. But when entering the dungeon, my inventory is cleared. When dying in a dungeon, any item that I have obtained while playing are wiped and I spawn back with my full kit reset. When leaving a dungeon, my inventory is cleared and reset to the inventory I had before entering.
(e.g. game rules)

**Link to the wiki article (in case it exists)**

**What did you already try?**
Tried changing gamerule keepInventory true
Tried doing same thing in config files, nothing worked.
**Relevant configuration files**
(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

config.yml :
```
configVersion: 20
language: english
enableEconomy: true
groupAdaptersEnabled: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
editInstanceRemovalDelay: 5
strictMovementCheckEnabled: true
secureMode:
  enabled: false
  openInventories: true
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
lobbyContainersEnabled: false
default: {}

```
