### ISSUE TITLE
Commands Give Errors

### ISSUE THREAD

**Issue by Davedave000** [DRE2N/DungeonsXL#906]
**Description**

Many commands seem to give an internal error when issued. I posted a screenshot of console below whenever that happens. (I used /dxl help for this one specifically, not sure if other commands give different results.)

**Reproduce**

(List steps to reproduce, e.g.:
1. Use /dxl help (Some other commands also work like /dxl leave.)
2. After issuing the command, chat says "An internal error occurred while attempting to preform this command"
3. Check console, you should get the same error message from above.

**Expected behavior**

When I use /help I expect to get a list of commands to reference.

**Screenshots / GIFs / videos**

![image](https://user-images.githubusercontent.com/56517317/97097254-cc2f7880-162b-11eb-817b-b5d535dd6d26.png)
![image](https://user-images.githubusercontent.com/56517317/97097329-78715f00-162c-11eb-880c-10f7bdb99ea9.png)
![image](https://user-images.githubusercontent.com/56517317/97097349-93dc6a00-162c-11eb-92c8-59b267efcc9d.png)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents so that others can see if there are any syntax errors.)

```
configVersion: 20
language: english
enableEconomy: true
groupAdaptersEnabled: false
chatEnabled: false
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: false
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
editInstanceRemovalDelay: 5
strictMovementCheckEnabled: false
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
lobbyContainersEnabled: false
default:
  keepInventoryOnEnter: true
  keepInventoryOnFinish: true
```
