### ISSUE TITLE
[End] signs don't work.

### ISSUE THREAD

**Issue by Davedave000** [DRE2N/DungeonsXL#907]
**Description**

Signs with the [End] tag on line one don't do anything.

**Reproduce**

1. Create a dungeon with a lobby, start and end point.
2. Use /dxl play and get to the end of the dungeon.
3. Trigger the [End] sign, nothing happens.

**Expected behavior**

When I trigger the [End] sign, I expect to be taken back to the main world where I started the dungeon.

**Screenshots / GIFs / videos**

Not Applicable

**Relevant configuration files**

```
configVersion: 20
language: english
enableEconomy: true
groupAdaptersEnabled: false
chatEnabled: false
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: false
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
editInstanceRemovalDelay: 5
strictMovementCheckEnabled: false
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
lobbyContainersEnabled: false
default:
  keepInventoryOnEnter: true
  keepInventoryOnFinish: true
```
