### ISSUE TITLE
You can take the GUI items out of the dungeon loot GUI

### ISSUE THREAD

**Issue by Davedave000** [DRE2N/DungeonsXL#908]
**Description**

You're able to take the two paper items and the stained glass out of the dungeon loot GUI.

**Reproduce**

1. Finish a dungeon with less than a page of rewards. (Not sure if it's fine with more than a page of rewards)
2. Take the paper or the stained glass and drag it into your inventory.
3. Close the GUI, you now have the paper and the stained glass.

**Expected behavior**

Clicking on items you shouldn't be able to take should make it snap back into place.

**Screenshots / GIFs / videos**

![image](https://user-images.githubusercontent.com/56517317/97112156-f15dce80-169f-11eb-90dc-55b5e04d655c.png)

**Relevant configuration files**

```
configVersion: 20
language: english
enableEconomy: false
groupAdaptersEnabled: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
editInstanceRemovalDelay: 5
strictMovementCheckEnabled: true
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
lobbyContainersEnabled: false
default:
  keepInventoryOnEnter: true
  keepInventoryOnFinish: true
```
