### ISSUE TITLE
Plugin is disabled for some reason?

### ISSUE THREAD

**Issue by Davedave000** [DRE2N/DungeonsXL#911]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

I installed the latest version of the plugin onto my server only to find that it's completely broken. The console says it's disabled for some reason and I can't figure out how to re-enable it.

**Reproduce**

1. Install 0.18-SNAPSHOT-1043 into your plugins folder.
2. Run the server.
3. Use /dxl, you get an error.

**Expected behavior**

I expected the plugin to be enabled when I install it onto my server.

**Screenshots / GIFs / videos**

![image](https://user-images.githubusercontent.com/56517317/97497942-8f63ca00-1928-11eb-8d62-fc32ec98a098.png)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```
configVersion: 20
language: english
enableEconomy: true
groupAdaptersEnabled: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
editInstanceRemovalDelay: 5
strictMovementCheckEnabled: true
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
lobbyContainersEnabled: false
default:
  keepInventoryOnEnter: true
  keepInventoryOnFinish: true
  keepInventoryOnEscape: false
  initialLives: 3
```
