### ISSUE TITLE
Requirements charge you for every floor.

### ISSUE THREAD

**Issue by Davedave000** [DRE2N/DungeonsXL#913]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

Even if you put the fee requirements in the first floor, DXL will still take money from your balance for every floor you visit.

**Reproduce**

1. Create a multifloor dungeon.
2. Add a config.yml file to the first map.
3. Add a 'feeMoney' requirement.
4. Playtest the dungeon without OP. It should charge you for each floor.

**Expected behavior**

It should only charge me for the first floor.

**Screenshots / GIFs / videos**

![image](https://user-images.githubusercontent.com/56517317/97539851-ec3e9f00-197f-11eb-8b83-7ef2324fb2dc.png)

**Relevant configuration files**

config.yml for the first floor:
```
requirements:
  forbiddenItems:
  - ENDER_PEARL
  - ELYTRA
  feeMoney: 9
```
yml file for the entire dungeon:
```
# The first floor the players enter.
# Needs at least lobby, ready, start and end signs.
startFloor: Craggy_Coast_1
endFloor: Craggy_Coast_6
floors:
- Craggy_Coast_2
- Craggy_Coast_3
- Craggy_Coast_4
- Craggy_Coast_5
floorCount: 2
removeWhenPlayed: true
overrideValues:
  timeToNextLoot: 2
  time: 6000
configVersion: 1

```
