### ISSUE TITLE
Can't figure out inventories

### ISSUE THREAD

**Issue by jc-pitt** [DRE2N/DungeonsXL#924]
**The feature you'd like to know more about**
I'm trying to figure out how to get players to keep their inventory when they enter/leave a dungeon.

**Link to the wiki article (in case it exists)**
https://github.com/DRE2N/DungeonsXL/wiki/game-rules

**What did you already try?**
I tried changing both the main plugin config and the specific dungeon config. I'm using multiverse inventories so I'm unsure if that could be an issue? If so, is there a way to fix it/make all dungeon worlds go to a group automatically without getting rid of multiverse inventories? (I can't afford bungeecord but there is more than one gamemode on my server and I want to make sure players can't carry items over between them)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

*Main plugin config*
```
configVersion: 20
language: english
enableEconomy: false
groupAdaptersEnabled: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
editInstanceRemovalDelay: 5
strictMovementCheckEnabled: true
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
lobbyContainersEnabled: false
default:
  keepInventoryOnEnter: true
  keepInventoryOnFinish: true
  foodLevel: false
 
```
*Dungeon Config ( /plugins/DungeonsXL/maps/dungeon/config.yml)*
```
  keepInventoryOnEnter: true
  keepInventoryOnFinish: true
```
