### ISSUE TITLE
How to allow players to keep inventory when they join dungeon

### ISSUE THREAD

**Issue by iTemmy** [DRE2N/DungeonsXL#992]
Making player join Dungeon with their inventory

(e.g. game rules)

https://github.com/DRE2N/DungeonsXL/wiki/game-rules

I have tried putting it into the config for the specific dungeon and tried putting it in the main config but I can't figure it out

```
configVersion: 20
language: english
enableEconomy: false
groupAdaptersEnabled: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
editInstanceRemovalDelay: 5
strictMovementCheckEnabled: true
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
lobbyContainersEnabled: false
default:
  keepInventoryOnEnter: true
  keepInventoryOnFinish: true

```
```
# Dungeon configuration of DungeonsXL (%dungeon name%.yml in
# DungeonsXL/scripts/dungeons/ folder)

# These values override the values of the
# main configuration file default section and the floor configuration files.
overrideValues:
  # Optionally all game rules of a floor config, like:
  keepInventoryOnEnter: true

# These values override the values of the
# main configuration file default section, but get overridwn by the floor configuration values.
defaultValues:
  # Optionally all game rules of a floor config, like:
  keepInventoryOnEnter : true
  
```
