### ISSUE TITLE
Key item CUSTOM Caliburn does not work

### ISSUE THREAD

**Issue by tiradorus** [DRE2N/DungeonsXL#996]
**Description**

Dungeon does dot detect the custom items from caliburn as KeyRequirement to entering the dungeon.

**Reproduce**

Just try to use Caliburns items as KeyItems and take a look onto the behavior of the plugin

**Expected behavior**

1 You have the KeyItem
2 You enter the dungeon
3 It remove your KeyItem

**Screenshots / GIFs / videos**

There you can see the condition shown when trying to entering the dungeon (Cf code below)
![Except](https://user-images.githubusercontent.com/13207813/111698759-8459f980-8837-11eb-8fa9-30aac305163c.png)

**Relevant configuration files**

There is the config.yml into the MAPS folder
```
requirements:
  groupSize:
    minimum: 1
    maximum: 3
  forbiddenItems:
    - CHORUS_FRUIT
    - ENCHANTED_GOLDEN_APPLE
    - GOLDEN_APPLE
    - ENDER_PEARL
    - ELYTRAS
    - BUCKET
    - WATER_BUCKET
    - LAVA_BUCKET
  keyItems:
    - STONE
    - CRYPTE
keepInventoryOnEnter: true
keepInventoryOnFinish: true
keepInventoryOnLeave: true
keepInventoryOnEscape: true
keepInventoryOnDeath: true
timeUntilKickOfflinePlayer: 0
```

Here is my 'crypte.yml' into custom items Caliburn

```
idType: LORE
material: ARMOR_STAND
meta:
  ==: ItemMeta
  meta-type: ARMOR_STAND
  display-name: '{"italic":false,"color":"white","extra":[{"bold":true,"color":"dark_aqua","text":"Clé
    de la crypte"}],"text":""}'
  lore:
  - '{"italic":false,"color":"white","text":""}'
  - '{"italic":false,"color":"white","extra":[{"color":"gray","text":"Clé de passage
    nécéssaire"}],"text":""}'
  - '{"italic":false,"color":"white","extra":[{"color":"gray","text":"pour entrer
    dans l\u0027instance"}],"text":""}'
  - '{"italic":false,"color":"white","extra":[{"extra":[{"color":"gray","text":"de
    la "},{"bold":true,"color":"gray","text":"Crypte"},{"color":"gray","text":"."}],"text":""}],"text":""}'
  ItemFlags:
  - HIDE_ATTRIBUTES
  internal: H4sIAAAAAAAAALWRzWqEMBSFrzs7UCiFLvqzCG66Kd12ncbbmVCjkmQjUqw4oQyIFbWLPtHga4wv1jiWGYqz7SYc+O7JOZe7AHDhSoiIaxQq85OQCs6yIJIIRep5D95u+8TKoSdrQ+q8bfMPQ6qhL4be6k1jpon686shpuoa05B1XrWkvN9UbZdXxe+AdZc5sWK3LVnzXXfG6kfvzYHrYzhX9DnATAkMNA+XjgsXBzi+Gffh7BUTJpNYowN3MysPNUrKNI9C6z7ypaSW+FmMUnClLFawSL1i32RscTv7CkO2sqapx+XfHjqJEVxBbRinwekduF6N3lOQSfqiJ3gzgxJjyuUUe36g+4O8p/98DfgBCXscbg8CAAA=
```
